name: redurx_sample
description: An example Todo app created with redurx

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_redurx: ^0.4.2+1
  built_value: ^6.3.1
  built_collection: ^4.1.0
  tuple: ^1.0.2
  todos_app_core:
    path: ../todos_app_core
  todos_repository_core:
    path: ../todos_repository_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.2.8
  built_value_generator: ^6.1.0
  source_gen: ^0.9.0+1
  test: ^1.6.0
  mockito: ^3.0.0
  flutter_driver:
    sdk: flutter
  integration_tests:
    path: ../integration_tests

flutter:
  uses-material-design: true