// Mocks generated by Mockito 5.4.6 from annotations
// in mvi_base/test/mvi_todos_list_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mvi_base/mvi_base.dart' as _i3;
import 'package:todos_repository_core/todos_repository_core.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeReactiveTodosRepository_0 extends _i1.SmartFake
    implements _i2.ReactiveTodosRepository {
  _FakeReactiveTodosRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_1 extends _i1.SmartFake implements _i3.User {
  _FakeUser_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TodoListInteractor].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoListInteractor extends _i1.Mock
    implements _i3.TodoListInteractor {
  @override
  _i2.ReactiveTodosRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeReactiveTodosRepository_0(
              this,
              Invocation.getter(#repository),
            ),
            returnValueForMissingStub: _FakeReactiveTodosRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ReactiveTodosRepository);

  @override
  _i4.Stream<List<_i3.Todo>> get todos =>
      (super.noSuchMethod(
            Invocation.getter(#todos),
            returnValue: _i4.Stream<List<_i3.Todo>>.empty(),
            returnValueForMissingStub: _i4.Stream<List<_i3.Todo>>.empty(),
          )
          as _i4.Stream<List<_i3.Todo>>);

  @override
  _i4.Stream<bool> get allComplete =>
      (super.noSuchMethod(
            Invocation.getter(#allComplete),
            returnValue: _i4.Stream<bool>.empty(),
            returnValueForMissingStub: _i4.Stream<bool>.empty(),
          )
          as _i4.Stream<bool>);

  @override
  _i4.Stream<bool> get hasCompletedTodos =>
      (super.noSuchMethod(
            Invocation.getter(#hasCompletedTodos),
            returnValue: _i4.Stream<bool>.empty(),
            returnValueForMissingStub: _i4.Stream<bool>.empty(),
          )
          as _i4.Stream<bool>);

  @override
  _i4.Stream<_i3.Todo> todo(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#todo, [id]),
            returnValue: _i4.Stream<_i3.Todo>.empty(),
            returnValueForMissingStub: _i4.Stream<_i3.Todo>.empty(),
          )
          as _i4.Stream<_i3.Todo>);

  @override
  _i4.Future<void> updateTodo(_i3.Todo? todo) =>
      (super.noSuchMethod(
            Invocation.method(#updateTodo, [todo]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addNewTodo(_i3.Todo? todo) =>
      (super.noSuchMethod(
            Invocation.method(#addNewTodo, [todo]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTodo(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTodo, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearCompleted([dynamic _0]) =>
      (super.noSuchMethod(
            Invocation.method(#clearCompleted, [_0]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<dynamic>> toggleAll([dynamic _0]) =>
      (super.noSuchMethod(
            Invocation.method(#toggleAll, [_0]),
            returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
            returnValueForMissingStub: _i4.Future<List<dynamic>>.value(
              <dynamic>[],
            ),
          )
          as _i4.Future<List<dynamic>>);
}

/// A class which mocks [UserInteractor].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserInteractor extends _i1.Mock implements _i3.UserInteractor {
  @override
  _i4.Future<_i3.User> login() =>
      (super.noSuchMethod(
            Invocation.method(#login, []),
            returnValue: _i4.Future<_i3.User>.value(
              _FakeUser_1(this, Invocation.method(#login, [])),
            ),
            returnValueForMissingStub: _i4.Future<_i3.User>.value(
              _FakeUser_1(this, Invocation.method(#login, [])),
            ),
          )
          as _i4.Future<_i3.User>);
}
