name: frideos_library
description: An example Todo app created with the frideos library

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter  
  frideos: ^0.5.0   
  todos_app_core:
    path: ../todos_app_core
  todos_repository_simple:
    path: ../todos_repository_simple

dev_dependencies:
  flutter_test:
    sdk: flutter 
  test: ^1.3.0
  mockito: ^3.0.0
  flutter_driver:
    sdk: flutter
  integration_tests:
    path: ../integration_tests

flutter:
  uses-material-design: true