// Mocks generated by Mockito 5.4.6 from annotations
// in signals_sample/test/todo_list_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todos_repository_core/src/todo_entity.dart' as _i4;
import 'package:todos_repository_core/src/todos_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TodosRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodosRepository extends _i1.Mock implements _i2.TodosRepository {
  @override
  _i3.Future<List<_i4.TodoEntity>> loadTodos() =>
      (super.noSuchMethod(
            Invocation.method(#loadTodos, []),
            returnValue: _i3.Future<List<_i4.TodoEntity>>.value(
              <_i4.TodoEntity>[],
            ),
            returnValueForMissingStub: _i3.Future<List<_i4.TodoEntity>>.value(
              <_i4.TodoEntity>[],
            ),
          )
          as _i3.Future<List<_i4.TodoEntity>>);

  @override
  _i3.Future<void> saveTodos(List<_i4.TodoEntity>? todos) =>
      (super.noSuchMethod(
            Invocation.method(#saveTodos, [todos]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
