name: todos_repository_flutter
description: An app-agnostic data source that can be used by all implementations

dependencies:
  flutter:
    sdk: flutter
  todos_repository:
    path: ../todos_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ">=2.2.3 <3.0.0"
