name: built_redux_sample
description: An example Todo app created with built_redux

dependencies:
  flutter:
    sdk: flutter
  flutter_built_redux: ^0.4.0
  built_redux: 7.4.1-dev
  built_value: ^5.2.0
  built_collection: ^3.0.0
  flutter_architecture_samples:
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter
  build: ^0.12.0
  build_runner: ^0.8.0
  built_value_generator: ^5.2.0
  source_gen: ^0.7.0
  test: ^0.12.0
  mockito: ">=2.2.0 <3.0.0"
  flutter_driver:
    sdk: flutter
  integration_tests:
    path: ../integration_tests

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
